---
services:
  web:
    image: ghcr.io/h5radar/web:latest
    container_name: h5radar-web
    ports:
      - "80:80"
  account:
    image: ghcr.io/h5radar/account:latest
    container_name: h5radar-account
    ports:
      - "8070:8070"
  radar:
    image: ghcr.io/h5radar/radar:latest
    container_name: h5radar-radar
    ports:
      - "8080:8080"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: h5radar-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HTTP_PORT: 8180
      KC_LOG_LEVEL: INFO
      KC_LOG_CONSOLE_OUTPUT: default
      KC_LOG: console
      KC_HTTP_ACCESS_LOG_ENABLED: true
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8180:8180"