#
# Package (build and test) application
#
name: Package application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get install yamllint -y
      - name: Lint docker-compose
        run: yamllint docker-compose.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run application
        run: |
          docker compose -f docker-compose.yml up -d
          echo "Waiting for service on localhost:80..."
          for i in {1..60}; do
            nc -z localhost 80 && break
            echo "Still waiting..."
            sleep 1
          done
          docker compose ps
        timeout-minutes: 3
